ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "usgs_extract"
  site-url: "https://caylor@ucsb.edu.github.io/usgs_extract"
  description: "A library for extracting table data from UGSG publications"
  twitter-card: true
  open-graph: true
  repo-branch: master
  repo-url: "https://github.com/caylor@ucsb.edu/usgs_extract"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/caylor@ucsb.edu/usgs_extract"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
